project_name: gosling
builds:
  - main: ./cmd/gosling
    binary: gosling
    goos:
      - windows
      - darwin
      - linux
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^repo:"
      - typo
      - Merge pull request
      - Merge branch
archives:
  - format_overrides:
      - goos: windows
        format: zip
snapcrafts:
  - id: gosling
brews:
  - tap:
      owner: leonidboykov
      name: homebrew-tap
    folder: Formula
    homepage: https://leonidboykov.github.io/gosling/
    description: HTML redirects generator
    test: system "#{bin}/gosling -v"
    install: bin.install "getmoe"
scoop:
  bucket:
    owner: leonidboykov
    name: scoop-bucket
  homepage: https://leonidboykov.github.io/gosling/
  description: HTML redirects generator
  license: MIT
dockers:
  - goos: linux
    goarch: amd64
    goarm: ""
    image_templates:
      - "leonidboykov/gosling:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "leonidboykov/gosling:{{ .Major }}.{{ .Minor }}"
      - "leonidboykov/gosling:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
