name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Build project
        run: go build ./cmd/gosling
        
      # Release tags
      - name: Docker Login
        uses: Azure/docker-login@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          username: leonidboykov
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          args: release --rm-dist
          key: ${{ secrets.GITHUB_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
