name: build

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.x
      - name: Build project
        run: go build ./cmd/gosling
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: leonidboykov
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --rm-dist
          key: ${{ secrets.GITHUB_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
